# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Guru3D.Afterburner
PackageVersion: 4.6.6
PackageLocale: en-US
Publisher: MSI Co., LTD
PublisherUrl: https://www.msi.com/Landing/afterburner/graphics-cards
PrivacyUrl: https://www.msi.com/page/privacy-policy
PackageName: MSI Afterburner
License: Freeware
ShortDescription: MSI Afterburner monitoring and GPU overclocking tool
Moniker: afterburner
Tags:
- gpu
- gpu-utility
- hardware
- hardware-utility
- utility
ManifestType: defaultLocale
ManifestVersion: 1.10.0
